---
name: Upgrade ubuntu
description: Upgrades ubuntu via apt
author: 5H3LL3H5
runs:
    using: composite
    steps:
        - id: display-os-version
          run: cat /etc/issue
          shell: bash
        - id: apt-update
          run: sudo apt-get update
          shell: bash
        - id: apt-dist-upgrade
          run: sudo apt-get -y dist-upgrade
          shell: bash
        - id: apt-autoremove
          run: sudo apt-get autoremove
          shell: bash
