# .pre-commmit-config.yaml
- repo: git@github.com:pecigonzalo/pre-commit-shfmt.git
  sha: master
  hooks:
    - id: shell-fmt
      args:
        - --indent=4
- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: v0.7.1.1
  hooks:
    - id: shellcheck
