name: "CI"
on: [push, pull_request]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Setting up BATS
        run: git clone https://github.com/bats-core/bats-core.git; cd bats-core; sudo ./install.sh /usr

      
      - name: Check out code
        uses: actions/checkout@v2
              
      - name: Running tests
        run: bats -r .
