name: 'Testing bash scripts.'
on: [push, pull_request]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setting up BATS
        uses: ./.github/actions/setup-bats-action
      - name: Running tests
        run: ~/bats-core/bin/bats --recursive --formatter tap --timing test 
        shell: bash
