---
name: Testing bash scripts.
on: [push, pull_request]
jobs:
    build:
        name: build
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v2
            - name: System update
              uses: ./.github/actions/upgrade-ubuntu-action
            - name: Setting up bats
              uses: ./.github/actions/setup-bats-action
            - name: Setting up bats-mock
              uses: ./.github/actions/setup-bats-mock-action
            - name: Setting up shellcheck
              uses: ./.github/actions/setup-shellcheck-action
            - name: Running shellcheck on source scripts
              run: shellcheck --shell=bash --severity=style --norc --external-sources get_mdr_all_langs.bash
            - name: Running shellcheck on test scripts
              run: shellcheck --shell=bash --severity=style --norc --external-sources test/tests.bats
              shell: bash
            - name: Running bats tests
              run: /usr/local/bin/bats --recursive --formatter tap --timing test
              shell: bash
