name: 'Testing bash scripts.'
on: [push, pull_request]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setting up Bats 
        uses: ./.github/actions/setup-bats-action
      - name: Setting up shellcheck 
        uses: ./.github/actions/setup-shellcheck-action
      - name: Running shellcheck 
        run: ~/shellcheck-stable/shellcheck --shell=bash --severity=style --norc --external-sources *.bash
        shell: bash
      - name: Running bats tests
        run: ~/bats-core/bin/bats --recursive --formatter tap --timing test 
        shell: bash
