name: 'Testing bash scripts.'
on: [push, pull_request]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setting up BATS
        uses: ./.github/actions/setup-bats-action
        with: 
          bats-version: '1.2.1'
      - name: Running tests
        run: bats --recursive --tap --timing test 
        shell: bash
